[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nomadz_payment = "FBMUQfqb8m4p8gBYcxrL255UWa5rWmFv4qEf2BBngZcd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "deploy.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pipeline.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "http://localhost:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
